# Generated by Django 5.2.17 on 2026-09-28 17:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(default='This prototype demonstrates page subscriptions and notifications between Wagtail and Zabbix.'),
        ),
    ]
